spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/person
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    showSql: true
    properties:
      hibernate.formatSql: true
logging:
  level.org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: trace


